# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RadioApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
	 pod 'Masonry'
	 pod 'BaiduMapKit'
	 pod 'MBProgressHUD', '~> 1.1.0'
     pod 'ReactiveCocoa','~>2.1.8'
     pod 'YYModel', '~> 1.0.4'
end
